remote_theme: pages-themes/minimal@v0.2.0

title: Anna Carolina Corrêa
description: My projects' portfolio
author: Anna Carolina Corrêa

logo: /assets/img/profile.png

email: annaccorrea1@hotmail.com
location: San Francisco, USA
linkedin: https://www.linkedin.com/in/annaccorrea
github: https://github.com/annacrr
