title: Anna Carolina Corrêa
description: My projects' portfolio
author: Anna Carolina Corrêa
theme: jekyll-theme-minimal

collections:
  projects:
    output: true
    permalink: /projects/:name/

email: annaccorrea1@hotmail.com
location: San Francisco, USA
linkedin_username: annaccorrea
github_username: annacrr
